name: "Ansible deploy k3s cluster"

on:
  # workflow_run:
  #   workflows: ["Terraform deploy node pool"]
  #   types:
  #     - completed
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  ansible-k3s-deploy:
    # if: github.event.workflow_run.conclusion == 'success'
    runs-on: iac
    env:
      ANSIBLE_INIT_PRIVATE_KEY: ${{ secrets.ANSIBLE_INIT_PRIVATE_KEY }}
        
    steps:
      - name: Checkout Ansible code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: Git clone k3s-io/k3s-ansible
        run: |
          git clone https://github.com/k3s-io/k3s-ansible.git
          cd k3s-ansible
          git checkout 1.2.1

      - name: Ansible ping
        run: |
          echo "$ANSIBLE_INIT_PRIVATE_KEY" > ansible_init_private_key
          chmod 600 ansible_init_private_key
          docker run --rm -v "$(pwd)/ansible:/workspace" \
          -v "$(pwd)/ansible_init_private_key:/ansible_init_private_key:ro" \
          -w /workspace \
          alpine/ansible:2.21.0 ansible all -i /workspace/k3s-cluster-inventory.yml --private-key /ansible_init_private_key -m ping
          shred -u ansible_init_private_key

      - name: Ansible deploy k3s
        run: |
          echo "$ANSIBLE_INIT_PRIVATE_KEY" > ansible_init_private_key
          chmod 600 ansible_init_private_key
          docker run --rm -v "$(pwd)/ansible:/workspace" \
          -v "$(pwd)/k3s-ansible:/k3s-ansible" \
          -v "$(pwd)/ansible_init_private_key:/ansible_init_private_key:ro" \
          -w /k3s-ansible \
          alpine/ansible:2.21.0 ansible-playbook -i /workspace/k3s-cluster-inventory.yml --private-key /ansible_init_private_key /k3s-ansible/playbooks/site.yml
          shred -u ansible_init_private_key
