name: "Build Proxmox Golden Image"

on:
  push:
    branches:
      - master
    paths:
      - 'packer/**'
  workflow_dispatch:

jobs:
  packer-build:
    name: "Packer Build"
    runs-on: iac
    
    env:
      PKR_VAR_pm_api_url: "https://192.168.0.2:8006/api2/json"
      PKR_VAR_pm_api_token_id: ${{ secrets.PVE_TOKEN_ID }}
      PKR_VAR_pm_api_token_secret: ${{ secrets.PVE_TOKEN_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: Create docker volume for packer operations
        run: |
          docker volume create packer-operations

      - name: Packer Init
        run: |
          docker run --rm -v $(pwd)/packer:/workspace -w /workspace \
            -v packer-operations:/packer-operations \
            -e PACKER_PLUGIN_PATH='/packer-operations' \
            hashicorp/packer:latest init .

      - name: Packer Validate
        run: |
          docker run --rm -v $(pwd)/packer:/workspace -w /workspace \
            -v packer-operations:/packer-operations \
            -e PACKER_PLUGIN_PATH='/packer-operations' \
            -e PKR_VAR_pm_api_url \
            -e PKR_VAR_pm_api_token_id \
            -e PKR_VAR_pm_api_token_secret \
            hashicorp/packer:latest validate .

      - name: Packer Build
        run: |
          docker run --rm -v $(pwd)/packer:/workspace -w /workspace \
            -v packer-operations:/packer-operations \
            -e PACKER_PLUGIN_PATH='/packer-operations' \
            -e PKR_VAR_pm_api_url \
            -e PKR_VAR_pm_api_token_id \
            -e PKR_VAR_pm_api_token_secret \
            hashicorp/packer:latest build -force .

      - name: Delete docker volume packer-operations
        run: |
          docker volume rm packer-operations --force

